/// <reference types="react" />
  import { ComponentType, SVGAttributes } from 'react';

  interface Props extends SVGAttributes<SVGElement> {
    color?: string;
    size?: string | number;
  }

  type Icon = ComponentType<Props>;
  export const VehiclesCrossover: Icon;
export const VehiclesMidsize: Icon;
export const VehiclesPickup: Icon;
export const VehiclesConvertible: Icon;
export const VehiclesSportsStroke: Icon;
export const VehiclesSide: Icon;
export const VehiclesCompactCrossover: Icon;
export const VehiclesSedanFront: Icon;
export const ArrowDownRight: Icon;
export const ArrowLeft: Icon;
export const ArrowLeftCircle: Icon;
export const ArrowRight: Icon;
export const ArrowRightCircle: Icon;
export const ArrowUp: Icon;
export const ArrowUpCircle: Icon;
export const ArrowUpLeft: Icon;
export const ArrowUpRight: Icon;
export const TruckPickupRed: Icon;
export const TruckPickupYellow: Icon;
export const TruckPickupBlue: Icon;
export const TruckPickupDefault: Icon;
export const SuvCrossoverRed: Icon;
export const SuvCrossoverYellow: Icon;
export const SuvCrossoverBlue: Icon;
export const SuvCrossoverDefault: Icon;
export const SuvMidsizeRed: Icon;
export const SuvMidsizeYellow: Icon;
export const SuvMidsizeBlue: Icon;
export const SuvMidsizeDefault: Icon;
export const SuvCompactCrossoverRed: Icon;
export const SuvCompactCrossoverYellow: Icon;
export const SuvCompactCrossoverBlue: Icon;
export const SuvCompactCrossoverDefault: Icon;
export const CoupeSportsRed: Icon;
export const CoupeSportsYellow: Icon;
export const CoupeSportsBlue: Icon;
export const CoupeSportsDefault: Icon;
export const CoupeConvertibleRed: Icon;
export const CoupeConvertibleYellow: Icon;
export const CoupeConvertibleBlue: Icon;
export const CoupeConvertibleDefault: Icon;
export const SedanFrontDefault: Icon;
export const SedanFrontNeutral: Icon;
export const SedanFrontRed: Icon;
export const SedanFrontYellow: Icon;
export const SedanFrontBlue: Icon;
export const SedanSideLine: Icon;
export const SedanSideNeutral: Icon;
export const SedanSideRed: Icon;
export const SedanSideYellow: Icon;
export const SedanSideBlue: Icon;
